;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        comment-dwim
        forward-sexp
        indent-for-tab-command
        kill-region
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        ))
