;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        backward-sexp
        comment-dwim
        counsel-yank-pop
        easy-kill
        easy-mark
        fill-paragraph
        forward-sexp
        indent-for-tab-command
        kill-region
        org-self-insert-command
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        avy-pop-mark
        counsel-M-x
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        ))
