;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        TeX-newline
        backward-sexp
        c-electric-delete-forward
        c-electric-slash
        cdlatex-dollar
        cdlatex-math-modify
        cdlatex-math-symbol
        cdlatex-pbb
        cdlatex-sub-superscript
        cdlatex-tab
        comment-dwim
        company-coq-maybe-exit-snippet
        coq-terminator-insert
        counsel-yank-pop
        crux-move-beginning-of-line
        delete-char
        easy-kill
        easy-mark
        electric-newline-and-maybe-indent
        fill-paragraph
        forward-char
        forward-sexp
        haskell-indentation-common-electric-command
        indent-for-tab-command
        kill-region
        markdown-cycle
        markdown-exdent-or-delete
        message-beginning-of-line
        message-tab
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        pg-protected-undo
        reftex-label
        self-insert-command
        transpose-sexps
        upcase-region
        xah-comment-dwim
        ))

(setq mc/cmds-to-run-once
      '(
        avy-pop-mark
        beginning-of-buffer
        counsel-M-x
        haskell-indentation-newline-and-indent
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        ivy-switch-buffer
        mac-mwheel-scroll
        mouse-drag-secondary
        ))
